baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = 'paige'

[params.paige]
color_scheme = "light"
credit = '<a class="link-secondary text-decoration-none" href="https://github.com/willfaught/paige">Paige Theme</a>'
external_link_new_tab = true
[params.paige.site]
disable_title = true
disable_menu = false
disable_reading_time = true
credit = '<a class="link-secondary text-decoration-none" href="https://github.com/willfaught/paige">Paige Theme</a>'

[params.paige.page]
disable_reading_time = true
disable_alert = false
credit = '<a class="link-secondary text-decoration-none" href="https://github.com/willfaught/paige">Paige Theme</a>'

[params.paige.list]
disable_reading_time = true
credit = '<a class="link-secondary text-decoration-none" href="https://github.com/willfaught/paige">Paige Theme</a>'

[params.paige.list_page]
disable_reading_time = true
disable_sections = true
